### ISSUE TITLE
About Progress Inference

### ISSUE THREAD

**Issue by YicongHong** [chihyaoma/selfmonitoring-agent#3]
Hello, I have read through all the codes in detailed especially the progress inference related functions in pano_agent.py. I am sorry but I cannot see how in the case of with or without beam search (i.e. set beam_size = 1), the rollback is implemented.

I have printed out the progress monitor output values and the agent's trajectory, even with a current p-value < last step p-value, the agent keeps to continue from the current point but not step back. 

Could you please explain this to me? Thank you so much!

I attached 1 inference example in the text file below.
[terminal_record.txt](https://github.com/chihyaoma/selfmonitoring-agent/files/2969427/terminal_record.txt)

**Comment by chihyaoma** [comment]
Hi,

Thank you for the feedback.

The Progress Inference is actually implemented similarly to how beam search work because of the computational efficiency, as indicated in the README. Therefore, please make sure that you use `beam_size=5` when turning on Progress Inference `progress_inference=1` (I have corrected this in the README).

If you are interested in rollback behavior of the agent, I would actually suggest you check out our follow-up work at CVPR (oral) here:
https://github.com/chihyaoma/regretful-agent

This repository provides an end-to-end learned rollback mechanism for the navigation agent.
